FROM node:alpine

# make the 'app' folder the current working directory
WORKDIR /app

# copy 'package.json' to install depedencies
COPY package*.json ./

# install depedencies
RUN npm install

# copy files and folders to the current working directory (i.e. 'app' folder)
COPY . .

CMD ["npm", "run", "serve"]